tunnel: <SEU_TUNNEL_ID_AQUI>
credentials-file: /home/nonroot/.cloudflared/<SEU_TUNNEL_ID_AQUI>.json

ingress:
  - hostname: api.seudominio.com
    service: http://backend:3000
    path: /api-docs

  - hostname: seudominio.com
    service: http://frontend:80

  - service: http_status:404
