server {
    listen 80;

    # Rota para a documentação da API do Backend
    location /api-docs {
        proxy_pass http://backend:3000/api-docs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rota para as demais chamadas da API (opcional, para centralizar)
    location /auth { proxy_pass http://backend:3000/auth; }
    location /users { proxy_pass http://backend:3000/users; }
    location /courses { proxy_pass http://backend:3000/courses; }
    location /uploads { proxy_pass http://backend:3000/uploads; }

    # Rota padrão: Todo o resto vai para o Frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
